import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const projectRoot = process.cwd();
const tokensPath = join(projectRoot, "tokens/kairo-88.tokens.json");
const themesPath = join(projectRoot, "tokens/kairo-88.themes.json");
const outputPath = join(projectRoot, "src/styles/foundations/tokens.css");

const cssVarNames = {
  colors: {
    bg: "color-bg",
    surface: "color-surface",
    surfaceRaised: "color-surface-raised",
    text: "color-text",
    textMuted: "color-text-muted",
    border: "color-border",
    borderStrong: "color-border-strong",
    primary: "color-primary",
    primaryText: "color-primary-text",
    accent: "color-accent",
    info: "color-info",
    success: "color-success",
    warning: "color-warning",
    danger: "color-danger"
  },
  effects: {
    shadowSm: "shadow-sm",
    shadowMd: "shadow-md",
    glowFocus: "glow-focus"
  }
} as const;

type Token<T> = {
  $value: T;
};

type FoundationTokens = {
  font: {
    family: {
      ui: Token<string>;
      display: Token<string>;
      mono: Token<string>;
    };
  };
  space: Record<string, Token<string>>;
  radius: Record<string, Token<string>>;
  motion: {
    duration: Record<string, Token<string>>;
    easing: Record<string, Token<number[]>>;
  };
  icon: {
    size: Record<string, Token<string>>;
    stroke: {
      standard: Token<string>;
    };
  };
};

type ThemeColorKey = keyof typeof cssVarNames.colors;
type ThemeEffectKey = keyof typeof cssVarNames.effects;

type ThemeDefinition = {
  colorScheme: string;
  colors: Record<ThemeColorKey, string>;
  effects: Record<ThemeEffectKey, string>;
};

type ThemeConfig = {
  defaultTheme: string;
  themes: Record<string, ThemeDefinition>;
};

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function tokenValue<T>(token: Token<T>): T {
  return token.$value;
}

function formatFontFamily(value: string): string {
  return value
    .split(",")
    .map((family) => family.trim())
    .map((family) => {
      if (/^".+"$/.test(family) || /^'.+'$/.test(family)) return family;
      if (/^[a-z-]+$/i.test(family)) return family;
      return `"${family}"`;
    })
    .join(", ");
}

function emitThemeVariables(theme: ThemeDefinition): string {
  const lines = [`  color-scheme: ${theme.colorScheme};`];

  for (const [key, varName] of Object.entries(cssVarNames.colors)) {
    lines.push(`  --k88-${varName}: ${theme.colors[key as ThemeColorKey]};`);
  }

  lines.push("");

  for (const [key, varName] of Object.entries(cssVarNames.effects)) {
    lines.push(`  --k88-${varName}: ${theme.effects[key as ThemeEffectKey]};`);
  }

  return lines.join("\n");
}

function emitFoundationVariables(tokens: FoundationTokens): string {
  const lines: string[] = [];

  lines.push(`  --k88-font-ui: ${formatFontFamily(tokenValue(tokens.font.family.ui))};`);
  lines.push(`  --k88-font-display: ${formatFontFamily(tokenValue(tokens.font.family.display))};`);
  lines.push(`  --k88-font-mono: ${formatFontFamily(tokenValue(tokens.font.family.mono))};`);
  lines.push("");

  for (const [name, token] of Object.entries(tokens.space)) {
    if (name === "0") continue;
    lines.push(`  --k88-space-${name}: ${tokenValue(token)};`);
  }

  lines.push("");

  for (const [name, token] of Object.entries(tokens.radius)) {
    if (name === "none") continue;
    lines.push(`  --k88-radius-${name}: ${tokenValue(token)};`);
  }

  lines.push("");

  for (const [name, token] of Object.entries(tokens.motion.duration)) {
    lines.push(`  --k88-duration-${name}: ${tokenValue(token)};`);
  }

  for (const [name, token] of Object.entries(tokens.motion.easing)) {
    lines.push(`  --k88-ease-${name}: cubic-bezier(${tokenValue(token).join(", ")});`);
  }

  lines.push("");

  for (const [name, token] of Object.entries(tokens.icon.size)) {
    lines.push(`  --k88-icon-${name}: ${tokenValue(token)};`);
  }

  lines.push(`  --k88-icon-stroke: ${tokenValue(tokens.icon.stroke.standard)};`);

  return lines.join("\n");
}

export function buildTokensCss(
  tokens: FoundationTokens = readJson<FoundationTokens>(tokensPath),
  themeConfig: ThemeConfig = readJson<ThemeConfig>(themesPath)
): string {
  const defaultTheme = themeConfig.themes[themeConfig.defaultTheme];
  const themeEntries = Object.entries(themeConfig.themes);
  const defaultSelector = `:root,\n[data-theme="${themeConfig.defaultTheme}"]`;
  const nonDefaultThemes = themeEntries.filter(([name]) => name !== themeConfig.defaultTheme);

  return `/* Generated by scripts/generate-css-tokens.ts. Do not edit manually. */
${defaultSelector} {
${emitThemeVariables(defaultTheme)}

${emitFoundationVariables(tokens)}
}

${nonDefaultThemes
  .map(([name, theme]) => `[data-theme="${name}"] {\n${emitThemeVariables(theme)}\n}`)
  .join("\n\n")}
`;
}

export function writeTokensCss(): void {
  writeFileSync(outputPath, buildTokensCss(), "utf8");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeTokensCss();
}
